### ISSUE TITLE
N/evalf gives up if a subexpression cannot be distinguished from zero

### ISSUE THREAD

**Issue by coproc** [diofant/diofant#1044]
Expressions being equal to zero always raise the exception `PrecisionExhausted` when trying to compute a numerical approximation:
```python
>>> from diofant import *
>>> e = sqrt(2)+1-1/(sqrt(2)-1)
>>> simplify(e)
0
>>> N(e)
...
diofant.core.evalf.PrecisionExhausted: Failed to distinguish the expression:

-1/(-1 + sqrt(2)) + 1 + sqrt(2)

from zero. Try simplifying the input, using chop=True, or providing a higher maxn for evalf
```
This is a behaviour specific to diofant and signals that the sign of the expression cannot be computed numerically - so far, so good. Unfortunately this also happens with nested expressions whose sign could be determined:
```python
>>> e2 = e**2 + 1
>>> simplify(e2)
1
>>> N(e2)
...
diofant.core.evalf.PrecisionExhausted: Failed to distinguish the expression:

-1/(-1 + sqrt(2)) + 1 + sqrt(2)

from zero. Try simplifying the input, using chop=True, or providing a higher maxn for evalf
```
I think that `evalf_add` (and other auxiliary functions) should catch this exception and see if they can gurantee that the value of an expressions stays away from zero when a subexpression is close to zero. The code instead of `terms = [evalf(...) for ...]` in `eval_add` could e.g. look like this:
```python
    ....
    terms = []
    for arg in v.args:
        try:
            t = evalf(arg, prec + 10, options)
        except PrecisionExhausted:
            t = (fzero, fzero, prec, prec) # not sure about the guaranteed precision here
        terms.append(t)
    ....
```

**Comment by skirpichev** [comment]
> This is a behaviour specific to diofant 

No, sympy will also raise such an exception, if you provide `strict=True` option to `evalf()`.  Diofant just has different defaults here.

> I think that evalf_add (and other auxiliary functions) should catch this exception

I'm not sure if catching that exception is safe.  E.g. it might be also raised on nonzero expression:
```
In [15]: (fibonacci(1000) - GoldenRatio**1000/sqrt(5)).n()                                                                           
---------------------------------------------------------------------------
PrecisionExhausted                        Traceback (most recent call last)
...
In [16]: (fibonacci(1000) - GoldenRatio**1000/sqrt(5)).n(maxn=1000)                                                                  
Out[16]: -4.60123853010113e-210
```

I think, nothing can be done here, this is not a bug.  That you really want - already implemented by the `chop` option.

Feel free to reopen this issue, if you have more arguments to convince me.
