### ISSUE TITLE
floor sometimes too optimistic or wrong

### ISSUE THREAD

**Issue by coproc** [diofant/diofant#1055]
Consider this expression simplifying to `1` and its computed integral part:
```python
>>> e = 1/(sqrt(2)-1) - sqrt(2); simplify(e)
1
>>> floor(e)
1
```
At first sight the result seems ok. But how can `floor` (and in the background `evalf`) know - without the simplified result - that the value is not just a little below `1`? The problem becomes evident when modifying the expression a little:
```python
>>> e1 = e - Rational(1, 10**15); simplify(e1)
999999999999999/1000000000000000
>>> floor(e1)
1
```
which is obviously wrong. For numbers equal (or very close) to integers the function `floor` should not be evaluated, I guess, (almost) like for this expression:
```python
>>> e2 = e - 1; simplify(e2)
0
>>> floor(e2)
-sqrt(2) - 1 + 1/(-1 + sqrt(2))
```
But shouldn't that be `floor(-sqrt(2) - 1 + 1/(-1 + sqrt(2)))`?

**Comment by skirpichev** [comment]
> Btw: floor(e2) currently returns e2 - while this should be floor(e2) - right?

Actually, @coproc, I don't think that's wrong.  `e2` is _indeed_ an integer, that was correctly determined by Diofant's assumption system.  The question is: should we **evaluate** this integer to represent it as an Integer instance or not.  (When it's a number, of course, i.e. has no free symbols.)

My guess is: no, we shouldn't.  The default, implicit, function evaluation rules (auto-simplification) - must be cheap.  But I'm not sure.  An alternative might be testing `is_zero` assumption first.

**Comment by skirpichev** [comment]
sympy/sympy#19940
