### ISSUE TITLE
Change convention for indexing coefficients of DUP

### ISSUE THREAD

**Issue by skirpichev** [diofant/diofant#1102]
For legacy reasons, the Diofant uses SymPy's way to represent the dense univariate polynomial DUP), namely - the leading coefficient (LC) is coming first.  I doubt, that this indexing gives some benefits from the performance point of view (simple exponent shift?), but clearly complicates things while porting published algorithms, which usually (always?) assume that the index 0 coefficient is the terminal coefficient (TC), not the leading one.

I think, it's a good time to change the convention.  And, maybe, restore `PolyElement.from_list()` function to make conversion from the dense recursive representation (former DMP case).

**Comment by skirpichev** [comment]
Well, I dig the git history, but I don't get yet any glue on why this ordering was chosen (except for the mentioned above shifts in exponents, i.e. `dup_lshift/dup_rshift`).

@jksuom, I would appreciate your opinion.  It's easy to change right now, as Diofant uses sparse representation, but I'm thinking about restoring the dense one for some cases, e.g. univariate polynomials over finite fields (see e.g. #1097).  Thus, low-level details of the DUP representation will be important again.

**Comment by jksuom** [comment]
I suspect that the descending order was chosen simply because that is how polynomials are often presented. Anyway, I cannot recall having seen anything that would make any notable difference in the algorithms. In Python, it is easy to scan the lists either way. If I should have started from scratch, I would probably have chosen the ascending order.

**Comment by skirpichev** [comment]
On Sat, Nov 28, 2020 at 01:24:58AM -0800, Kalevi Suominen wrote:
>    I suspect that the descending order was chosen simply because that is how
>    polynomials are often presented.

Well, most (all?) books I've read use
a_0 + a_1 x + ... a_n x^n
convention.

>    Anyway, I cannot recall having seen
>    In Python, it is easy to scan the lists either way.

My concern was not scanning, but removing/adding elements.  AFAIK, for k
elements & list len = n - it's O(k) only from the end (and this is
exactly what dup_[lr]shift() do).  Though, I don't see too much
lshift/rshift calls in the code.

**Comment by jksuom** [comment]
> I don't see too much lshift/rshift calls in the code.

I have seldom come across those calls when looking into the algorithms.

**Comment by skirpichev** [comment]
Yes, mostly for real roots isolation and in the dup_mul() (Karatsuba branch).

BTW, [Maple](https://www.maplesoft.com/support/help/Maple/view.aspx?path=PolynomialTools%2fCoefficientVector) (per default) and [Mathematica](https://reference.wolfram.com/language/ref/CoefficientList.html) are using the reversed (wrt SymPy) convention.
