### ISSUE TITLE
Is it better to add typing hint?

### ISSUE THREAD

**Issue by wuyudi** [diofant/diofant#1109]
I notice that there aren't much typing hints, and since `diofant` requires 3.7 or higher, so add typing maybe better?

**Comment by skirpichev** [comment]
Yes, I would consider such PRs.  Right now, I run mypy in CI only for domains/polys submodules.

**Comment by skirpichev** [comment]
I'm not sure how to improve situation further (mypy diofant now pass).  Please reopen issue if you know.
