### ISSUE TITLE
(x/abs(sqrt(1 - x**2))).limit(x, oo) is -1 (should be 1)

### ISSUE THREAD

**Issue by skirpichev** [diofant/diofant#1216]
c.f.
```
In [12]: (x/abs(sqrt(x**2 - 1))).limit(x, oo)
Out[12]: 1
```

Another wrong example:
```
In [13]: e1 = (4*x - 2)/abs(sqrt(4 - 4*(2*x - 1)**2))
In [14]: e1.limit(x, oo)
Out[14]: -1
```

**Comment by anutosh491** [comment]
A related issue here which neither sympy nor diofant can solve as of now ,is series of expressions of type `Pow` where there are two branches or some discrepancy between negative and positive values . 
Consider this 
```
>>> from diofant import *
>>> x = Symbol('x', negative =True)
>>> 1/Abs(sqrt(1 - (-1 + 1/x)**2))
1/Abs(sqrt(-(-1 + 1/x)**2 + 1))
>>> _.series(x)
-x - x**2 - 3*x**3/2 - 5*x**4/2 - 35*x**5/8 + O(x**6)
>>>
>>>
>>>
>>> x = Symbol('x', positive=True)
>>> 1/Abs(sqrt(1 - (-1 + 1/x)**2))
1/Abs(sqrt(-(-1 + 1/x)**2 + 1))
>>> _.series(x)
-x - x**2 - 3*x**3/2 - 5*x**4/2 - 35*x**5/8 + O(x**6)
```
Answer from wolfram 
![image](https://user-images.githubusercontent.com/87052487/160133446-c081ecfb-6e77-4c80-89a7-3c92454358c7.png)

I plan to include this in my Gsoc 22' proposal but am not fully sure what's the best and mathematically correct approach here . Let me know if you know of a method to approach this (which is mathematically correct in all sense) or what is going wrong in `diofant `  @skirpichev

**Comment by skirpichev** [comment]
Abs._eval_nseries() method is wrong.
```
In [14]: abs(sqrt(x**2 - 1))._eval_nseries(x, 2, None).expand()
Out[14]: 
      2        
     x     ⎛ 4⎞
-1 + ── + O⎝x ⎠
     2         
```
