### ISSUE TITLE
Rename project and adapt imports (sympy -> diofant)

### ISSUE THREAD

**Issue by skirpichev** [diofant/diofant#135]
- [x] move project to diofant/diofant
- [x] update rtfd.io docs to use new domain, https://github.com/diofant/diofant/pull/270
- [x] update top-level docs like README.rst, CONTRIBUTING.rst..., https://github.com/diofant/diofant/pull/270
- [x] merge sympy backports, #275, ?
- [x] move sympy dir -> diofant, fix imports, setup.* and docs, https://github.com/diofant/diofant/pull/315
- [ ] alpha release, https://github.com/diofant/diofant/pull/318

**Comment by smichr** [comment]
pycas? An unrelated project is no longer maintained [here](https://github.com/ryanfox/pycas).

**Comment by skirpichev** [comment]
As I'm aware about the IPython's history, so probably it would be wise to avoid
"py" suffixes (or prefixes, whatever).   Anyway, unless Guido change insane integer
division (int/int -> float) - bare Python wouldn't be suitable for an interactive CAS.

**Comment by skirpichev** [comment]
AFAIR Diophantus is often credited for first using of algebraic notation (and symbols).

Maybe it's not too saucily to name this software in his memory?  E.g. as "Diofant" (shortest variant, I think): this is a transliteration of Диофант, from Russian.

@smichr, what do you think?
