### ISSUE TITLE
NotImplementedError: 3 element rule (corner): ('OO', 'OO', 'A1') in _traverse_quadrants()

### ISSUE THREAD

**Issue by skirpichev** [diofant/diofant#1426]
```
In [4]: R, x = ring('x', ZZ)

In [5]: R._count_complex_roots(R.from_list([1, 0, 1]), inf=(0, -1), sup=(0, 2))
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[5], line 1
----> 1 R._count_complex_roots(R.from_list([1, 0, 1]), inf=(0, -1), sup=(0, 2))

File ~/src/diofant/diofant/polys/rootisolation.py:1787, in _FindRoot._count_complex_roots(self, f, inf, sup, exclude)
   1783     s, t = B, B
   1785 f1, f2 = new_ring._real_imag(f)
-> 1787 return _get_rectangle(f1, f2, (u, v), (s, t), exclude)[0]

File ~/src/diofant/diofant/polys/rootisolation.py:548, in _get_rectangle(f1, f2, inf, sup, exclude)
    545 Q_L3 = _intervals_to_quadrants(I_L3, f1L3, f2L3, s, u)
    546 Q_L4 = _intervals_to_quadrants(I_L4, f1L4, f2L4, t, v)
--> 548 T = _traverse_quadrants(Q_L1, Q_L2, Q_L3, Q_L4, exclude=exclude)
    550 N = _winding_number(T, f1L1.ring.domain)
    552 I_L = I_L1, I_L2, I_L3, I_L4

File ~/src/diofant/diofant/polys/rootisolation.py:481, in _traverse_quadrants(Q_L1, Q_L2, Q_L3, Q_L4, exclude)
    479         rules.append((_rules_ambiguous[qq], corners[(j, i)]))
    480     else:
--> 481         raise NotImplementedError(f'3 element rule (corner): {qq}')
    483 q1, k = Q[0], 1
    485 while k < len(Q):

NotImplementedError: 3 element rule (corner): ('OO', 'OO', 'A1')
```

See also https://github.com/sympy/sympy/issues/14738.

**Comment by skirpichev** [comment]
@oscarbenjamin, this issue is still relevant for SymPy too.  What do you think on this approach: https://github.com/diofant/diofant/pull/1428?

**Comment by oscarbenjamin** [comment]
I haven't looked through the complex root finding code to understand it. It looks overly complicated to me in general though.

I would have thought that rational roots could just be handled separately. Then you have one set of routines for counting roots along rational line segments and another for counting roots in the interior of a rectangle or something.

**Comment by oscarbenjamin** [comment]
Maybe counting roots in a rectangle of zero width can just transform to counting roots on the real line. If you want to count roots of `p(x)` in `a + b*i` to `a + c*i` then that is equivalent to counting roots of `p(x + a)` in `b*i` to `c*i`. Then that is equivalent to counting roots of `p(i*(x + a))` in `[-c, -b]`.

**Comment by skirpichev** [comment]
> It looks overly complicated to me in general though.

Algorithm paper is 6 pages long.

> I would have thought that rational roots could just be handled separately.

I doubt that factorization over ground domain will be a performance boost.  Rather, authors suggest to avoid even square-free factorization.

> Then you have one set of routines for counting roots along rational line segments and another for counting roots in the interior of a rectangle or something.

The problem related rather not with rational roots, but with degenerate rectangles (a line segment), where at least one corner ends at polynomial root (in SymPy this can be only a point with rational coordinates, but Diofant supports real algebraic numbers too).  If not, routine works, but at cost of some repeated computations.

> Maybe counting roots in a rectangle of zero width can just transform to counting roots on the real line.

Yep.  That was an idea I was trying to outline above.

This is already used in Diofant to solve a limited problem: sorting roots with a common real part:
https://github.com/diofant/diofant/blob/58fa54d373498bb417ae3189fb2ff0df4e8b60ec/diofant/polys/rootisolation.py#L892-L911
