### ISSUE TITLE
Evalf can increase prec for Floats!

### ISSUE THREAD

**Issue by skirpichev** [diofant/diofant#161]
Probably we should keep Floats for input/output only.  For example, multiple precision
math with Floats currently doesn't have any sense.  Too easy get a wrong answer:

```
In [1]: n = sin(1)**2 + cos(1)**2 - 1
In [2]: f = n.evalf()
In [3]: f
Out[3]: -0.e-124
In [4]: f._prec
Out[4]: 1
In [5]: f2 = f.evalf()
In [6]: f2
Out[6]: -3.78182804184504e-124
In [7]: f2._prec
Out[7]: 53
```

@smichr, I think you are most knowledgeable person for evalf module.  Do you think it's an issue for Sympy?!

**Comment by smichr** [comment]
It's a known issue. The same bit me a few days ago when I realized that the `is_comparable` routine was faltering because it reevaluated a prec=1 Float and got higher precision. I'm not sure you would want to disable this ability, though, since I think it's necessary in doing some computations e.g. in order to get 5 digits of precision you need to use numbers with more than 5 digits of precision to do the calculation or else roundoff takes over. What I do think might be good, however, is to keep track of the original precision separate from the artificial precision.

**Comment by skirpichev** [comment]
> It's a known issue.

Perhaps I miss the bugreport in ~2k of open issues for the sympy.  Maybe wrong keywords for search...

> I'm not sure you would want to disable this ability

For sure, I want.  "Wrong answer" - issue of highest severity.

Perhaps, I should guard all places where we ask to increase precision and raise an
exception if it can't be done for some prec value (i.e. for Floats).

What I don't understand - why Float's are in the core?  They are inexact, they
violate many algebraic properties that core assume (i.e. distributivity).

**Comment by skirpichev** [comment]
> The same bit me a few days ago when I realized that the is_comparable routine was faltering because it reevaluated a prec=1 Float and got higher precision.

btw, I suspect, I did a similar workaround in https://github.com/skirpichev/omg/pull/163

**Comment by skirpichev** [comment]
@smichr, I believe this issue was fixed in the linked pull request.

My solution forbids "increase" precision with evalf, but you still can do this with class constructor.  E.g.:
```python
In [1]: Float(0.3, 1)
Out[1]: 0.3
    
In [2]: Float(_1, 5)
Out[2]: 0.30078
    
In [3]: _1.evalf(5)
Out[3]: 0.3
```

Regarding your point

> in order to get 5 digits of precision you need to use numbers with more than 5 digits of precision to do the calculation or else roundoff takes over.

That should be a problem if you can calculate above numbers with additional precision.  But for Float's - it's not the case.  If you increase prec for a Float - this will be an entirely new number (so, doing this is fine for Float.\_\_new\_\_).  And in the final answer you will get just 5 digits of garbage.
