### ISSUE TITLE
Inconsistency for parametric solutions with solve()

### ISSUE THREAD

**Issue by skirpichev** [diofant/diofant#427]
If we have one equation, that doesn't have symbols solved for:
```python
In [10]: solve([1], x)
Out[10]: []

In [11]: solve([1 + y], x)
Out[11]: []
```
But for several equations:
```python
In [12]: solve([1 + y, x - y], x)
Out[12]: [{x: y}]
```

It should be ``[]`` as well.

**Comment by smichr** [comment]
I noticed a similar issue when trying to solve for undetermined coefficients: perhaps unrelated but I haven't tracked it down too hard:

```
>>> solve(a*x**2+b*x-(2*x**2),a,b)
{a:2,b:0} 
>>> solve(a*x**2+b*x+c*y**2-(2*x**2-3*y**2),a,b,c)
[{a:1/x**2*(−b*x+2*x**2−y**2*(c+3))}] 

```

**Comment by skirpichev** [comment]
@smichr, support for solving undetermined coefficients with ``solve()`` was removed recently in the Diofant.  So, I don't think is related somehow.

This is consistent, I think:
```
In [3]: solve(a*x**2+b*x-(2*x**2),a,b)
Out[3]: 
⎡⎧     b    ⎫⎤
⎢⎨a: - ─ + 2⎬⎥
⎣⎩     x    ⎭⎦

In [4]: solve(a*x**2+b*x+c*y**2-(2*x**2-3*y**2),a,b,c)
Out[4]: 
⎡⎧             2    2        ⎫⎤
⎢⎪   -b⋅x + 2⋅x  - y ⋅(c + 3)⎪⎥
⎢⎨a: ────────────────────────⎬⎥
⎢⎪               2           ⎪⎥
⎣⎩              x            ⎭⎦

```

**Comment by skirpichev** [comment]
Ok, I think ``solve([1 + y, x - y], x)`` output is wrong.  It should be ``[]``.
