### ISSUE TITLE
Clarify the license of Diofant

### ISSUE THREAD

**Issue by certik** [diofant/diofant#445]
The BSD license in SymPy:

https://github.com/sympy/sympy/blob/d29d13a556e9e2c5622edfd345e4e99b9089a980/LICENSE

requires to "... retain the above copyright notice, this list of conditions ...", however the Diofant license modified the `c` clause:

https://github.com/diofant/diofant/blob/e97a1ee507cc66e147d92160c5c24a5cb88eb54b/LICENSE

I think that might be problematic, but I am not a lawyer. Regarding adding things to the copyright, I think that's probably fine.

@skirpichev, it would be helpful if you could please clarify the situation. The standard way of dealing with this, and also the way I dealt with it in https://github.com/sympy/sympy/pull/10531, is to simply copy the original license, intact, somewhere, and then add a new license, e.g. in SymPy, I copied your license, intact, and then kept the SymPy license, and finally I clarified which patches are covered by your license and which are not. So one way that would make this clear is if you copied the SymPy license, unmodified, and then added your own license, and further indicate which code or which patches are covered by each. Or if it's too complicated, I think you can just say "this project uses code from SymPy that was covered by SymPy's license:" and paste the license there or something like that.

That way there is no confusion to what code you own the copyright to, and what you don't. You own the copyright to your own code in Diofant, but you do not own copyright to SymPy's code (except your own patches that are merged in SymPy).

**Comment by skirpichev** [comment]
> Regarding adding things to the copyright, I think that's probably fine.

I believe so.  The difference in c) clause is emphasized here: "Neither the name **of Diofant**, or SymPy nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission."

In fact, I can drop bold'ed part, if you really insist.

> The standard way of dealing with this

Standardized by whom?

I only follow license terms, which don't changed.  (For just one commit - the copyright statement of SymPy Development Team was changed to include 2017 year...)  And additional copyright statement was added for this derived product.

> is to simply copy the original license, intact, somewhere, and then add a new license

And than you copy this license intact, append to your license.  Next round I will take your new license, append to mine and so on...

> further indicate which code or which patches are covered by each

No.  All code in this project - covered by it's license.  For code, backported from SymPy - it works too.  It doesn't make sense to keep a separate license for this stuff especially under SymPy's copyright&terms only.  If you want code on such terms - you can get this code from SymPy repo, right?  But if you want that code from this project and not SymPy - probably there are some changes here...  Additional copyright statement - is a price for such changes.

If you think that there is violation SymPy license terms somewhere - please better explain why.  But right now, I don't think so.

The history of code is an important thing, and I would like to improve this.  Right now, I preserve commit ownership, add links to related pr's in SymPy, emphasize changes I made on some commits and so on.  Bah, even "SymPy Development Team" listing was updated to include new contributors...  (Probably, in future I'll replace this section of docs with a short reference to your list of contributors.)

Given that this project has much less resources than SymPy, I think - in this way it doesn't violate nor SymPy license terms, nor just ethic norms.  (Esp. if we compare all this with SymPy practice of merging my changes without any acknowledgement...)

Let me know if you think that my LICENSE file is wrong or if I should change something in my practice of merging SymPy's stuff (how to document it, add credits properly and so on).  Given my comments above.

**Comment by certik** [comment]
My understanding is that you can use any license you want for Diofant (e.g. your current license is fine), you just have to "... retain the above copyright notice, this list of conditions ..." (from the SymPy license) somewhere in the documentation. When I said "standard", that's just my subjective feeling, e.g. if you look at some apps in Android, they typically just list all the open source licenses in the About section.

The way I offered above (i.e. simply copy the SymPy license somewhere in docs) is just one simple way to resolve it, then nobody can attack it. But it's not the only way.

Your way of resolving it is that you add yourself into the copyright statement (I think that's fine), but you also added Diofant into the `c` clause, and I am not sure about that. If you remove it, then I think that fixes it.

Again, I think this is a relatively minor thing, but since we are making sure we follow the licenses properly in both projects, I think it should be resolved, one way or another.

**Comment by skirpichev** [comment]
> Your way of resolving it is that you add yourself into the copyright statement (I think that's fine), but you also added Diofant into the c clause, and I am not sure about that.

I doubt it's an issue.  Your copyright is there, list of conditions is there, nothing removed.  All your license terms - are there.  Nothing prevents me from changing license to any compatible with your original one by imposing additional restrictions, which do not violate your terms.

> If you remove it, then I think that fixes it.

But let me know if you really insist on this, then we can ask on SO.

BTW,
```
Patches by Sergey B Kirpichev <skirpichev@gmail.com> merged after January 1,
2016 are licensed as:
```

I didn't send you any patches (except of course, code in sympy/sympy#10531, for which you have explicit permission to use it on SymPy terms).

I think here you should quote patch source (i.e. github project https://github.com/diofant/diofant/).  And you must sync LICENSE, of course.

**Comment by skirpichev** [comment]
Ok, let me know if you insist on removing Diofant from the 'c' clause.  Then we can ask lawyers somewhere, as your arguments for this not convinced me yet.

Please take into account also my comments in last reply.  It looks like I submitted some work to your project, which is not the case.  I believe, you should quote patch source here.  (btw, even that not all commits in the diofant - have me in "Author" header.)

**Comment by skirpichev** [comment]
@certik, that's how looks list of your contributors:
![1](https://cloud.githubusercontent.com/assets/2155800/23205260/a4172b80-f902-11e6-8c2e-671c5341477d.png)
Apparently, there is some content, but I'm unable to "expand" it in my browser (tested with firefox and epiphany in the Debian stable).

I think, it would be better, if you fix this issue, before I put link to list of your contributors in the Diofant docs.  In your dev version this doesn't appear.  Is [that link](http://docs.sympy.org/dev/aboutus.html#sympy-development-team) - a correct up-to date link which lists your contributors?  I would prefer a stable version, as it's much more likely that it would be available for readers.

**Comment by certik** [comment]
As far as I am concerned, I do not insist you fix the `c` clause. If you ask some lawyers, please update this issue, I would like to know, but I don't have time to do this myself.

Regarding the list of authors, the up-to-date list is this one: https://github.com/sympy/sympy/blob/master/AUTHORS, we have a script that maintains it: https://github.com/sympy/sympy/blob/62b1996e353fedc1e3fb51f626ffaae9583b74a6/bin/authors_update.py, in there you can see that we strictly follow the git history, except a few changes at the beginning, due to the fact that we started with svn and maintained the history by hand. And we remove people who explicitly asked me to be removed from that list. If these people ask me to be added back in, I'll be happy to add them back in.
So that's an accurate, up-to-date list.

**Comment by certik** [comment]
Regarding the https://github.com/sympy/sympy/pull/10531, is this text ok with you:


```
Patches by Sergey B Kirpichev <skirpichev@gmail.com> merged after January 1, 2016 were taken from the Diofant project (https://github.com/diofant/diofant/) and are licensed as:

....
```

Regarding your question about syncing the license --- wouldn't it be the case that the license, let's call it A, that applies to the code at the point we merge the PR, but once it's merged, if you change the license to Diofant from A to B, then sympy or anyone else can take the code from sympy and distribute under A. But they can also take it from Diofant and distribute under B. So I don't think we have to sync the license after it gets merged. Or what exactly did you mean by syncing the license?

**Comment by skirpichev** [comment]
> As far as I am concerned, I do not insist you fix the c clause.

Ok, then I'll keep this.

> https://github.com/sympy/sympy/blob/master/AUTHORS  that's an accurate, up-to-date list.

Ok, I'll use this url.  Thank you.

> is this text ok with you

I think you can omit my name, something like this "Patches, taken from the Diofant project <url> are licensed as ...".  But if you are sure - you want only my commits - it's probably fine as is.

> So I don't think we have to sync the license after it gets merged.

Yes.  But you must sync it, if you get another piece of code, from updated repo.  Probably, at least copyright years will be different.

**Comment by certik** [comment]
I updated https://github.com/sympy/sympy/pull/10531 based on your comment. Let me know if it looks good to you.

**Comment by skirpichev** [comment]
Good, thank you.

**Comment by certik** [comment]
@skirpichev thanks for approving it.
