### ISSUE TITLE
Feature request: Provide a way to run from the repo without installing anything

### ISSUE THREAD

**Issue by jondo** [diofant/diofant#450]
I have just cloned diofant and would like to run some tests.
Is there an equivalent of SymPy's `bin/isympy`, or should I use `venv` to avoid changes to my environment?

**Comment by skirpichev** [comment]
> Is there an equivalent of SymPy's bin/isympy, or should I use venv to avoid changes to my environment?

No, there is no isympy-like tool.  You should configure ipython, if yoi would like to work interactively.

Please also read [installation instuctions](http://diofant.readthedocs.io/en/latest/install.html).

> `ImportError: No module named 'strategies'. What am I missing?

Please read installation instuctions](http://diofant.readthedocs.io/en/latest/install.html), especially part ["from fources"](http://diofant.readthedocs.io/en/latest/install.html#from-sources).  This should be enough to install all required dependencies.

Let me know, if this doesn't answer your question well or you think that there is a documentation issue.

**Comment by skirpichev** [comment]
BTW, it's my usual IPython config (Diofant-specific part):
```python
c = get_config()
c.InteractiveShellApp.exec_lines.append("""
import IPython as ip, diofant, os
from diofant.interactive.session import IntegerWrapper
app = ip.get_ipython()
app.ast_transformers.append(IntegerWrapper())
del ip, app, os, IntegerWrapper, diofant
from diofant import *
x, y, z, t = symbols('x y z t')
k, m, n = symbols('k m n', integer=True)
f, g, h = symbols('f g h', cls=Function)
""")
```

Ast transformer IntegerWrapper - wrap builtin int with Diofant's type Integer.  There is also another transformer, AutomaticSymbols, which create missing symbols automatically.

**Comment by jondo** [comment]
OK, I now used pip in a venv to install everything locally. Thank you for your example config!

**Comment by skirpichev** [comment]
I did some improvements for installation documentation in #455.  Let me know if something else on this subject is not clear enough.

**Comment by skirpichev** [comment]
Now you can run the ``python -m diofant`` to get CLI, see docs.
