### ISSUE TITLE
rsolve should handle hypergeometric inhomogeneous terms

### ISSUE THREAD

**Issue by pedritomelenas** [diofant/diofant#451]
It seems that so far `rsolve` can only handle rational inhomogeneous part: `rsolve( x(n)-2*x(n-1)-3**n, x(n),[1])` yields
```
ValueError: Inhomogeneous part should be a rational function of 'n', got '3**n'
```
It could be nice to have also parts of the form `a^nf(n)` with `a` a positive integer and `f(n)` a polynomial, as in `sympy` where `rsolve( x(n)-2*x(n-1)-3**n, x(n),[1])` ouputs 
```
-2*2**n + 3*3**n
```
Thank you,
Pedro

**Comment by skirpichev** [comment]
I think, that's a (trivial) bug.  Current implementation should work for hypergeometric terms too.

Also, instead of raising ValueError - there should be (for non-hypergeometric terms) NotImplementedError instead.

**Comment by skirpichev** [comment]
Issue retitled.  Let me know if you think it's not accurate now.

**Comment by pedritomelenas** [comment]
Better. Thanks

**Comment by pedritomelenas** [comment]
Thanks, now `rsolve(x(n)-2*x(n-1)-3**n,x(n),[1])` works. 
However I cannot make it to work for `n*3**n`: `rsolve(x(n)-2*x(n-1)-3**n*n,x(n),[1])` yields an AttributeError.
Thank you,
Pedro

**Comment by skirpichev** [comment]
``hypersimp()`` call on line 547  fails.  If you make ``simplify(g)`` - it works:
```python
In [1]: rsolve(f(n)-2*f(n-1)-3**n*n, f(n),[1])
Out[1]: 
   n    n + 1        
7⋅2  + 3     ⋅(n - 2)
```

However, I think this should be a separate issue.

**Comment by skirpichev** [comment]
#456
