### ISSUE TITLE
Solve the rational inequality abs((x-1)/(x-5)) <= 1/3

### ISSUE THREAD

**Issue by jondo** [diofant/diofant#453]
Testing the current Git master, I see:

```python
In [1]: import diofant as df

In [2]: x = df.symbols('x', real=True)

In [3]: df.solve_univariate_inequality(abs((x-1)/(x-5)) <= 1/3, x)
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-12-a861138780c5> in <module>()
----> 1 df.solve_univariate_inequality(abs((x-1)/(x-5)) <= 1/3, x)

/home/robert/bin/diofant/diofant/solvers/inequalities.py in solve_univariate_inequality(expr, gen, relational)
    378         singularities = solve(d, gen, check=False)
    379     else:
--> 380         solns = solve(e, gen, check=False)
    381         singularities = []
    382         for d in denoms(e):

/home/robert/bin/diofant/diofant/solvers/solvers.py in solve(f, *symbols, **flags)
    767     ###########################################################################
    768     if bare_f:
--> 769         solution = _solve(f[0], *symbols, **flags)
    770     else:
    771         solution = _solve_system(f, symbols, **flags)

/home/robert/bin/diofant/diofant/solvers/solvers.py in _solve(f, *symbols, **flags)
   1017         result = set()
   1018         for n, (expr, cond) in enumerate(f.args):
-> 1019             candidates = _solve(expr, *symbols, **flags)
   1020             for candidate in candidates:
   1021                 if candidate in result:

/home/robert/bin/diofant/diofant/solvers/solvers.py in _solve(f, *symbols, **flags)
   1285 
   1286     if result is False:
-> 1287         raise NotImplementedError('\n'.join([msg, not_impl_msg % f]))
   1288 
   1289     if flags.get('simplify', True):

NotImplementedError: 
No algorithms are implemented to solve equation Piecewise(((x - 1)/(x - 5), x - 1 >= 0), ((-x + 1)/(x - 5), true)) - 1/3
```

(This corresponds to https://github.com/sympy/sympy/issues/9565, which [recently regressed](https://github.com/sympy/sympy/issues/12095).)

**Comment by skirpichev** [comment]
``solve_univariate_inequality()`` is a badly written heuristics.  Perhaps, I should remove its export.

You should use ``reduce_inequalities()`` (like Mathematica's Reduce) to work with inequalities.  This one works as expected:
```python
In [7]: df.reduce_inequalities(abs((x - 1)/(x - 5)) <= df.Rational(1, 3), x)
Out[7]: -1 ≤ x ∧ x ≤ 2
```

But solving of mentioned equation with abs (see traceback) was working for SymPy 0.7.6, so that's a regression in ``solve()``.  Thank you.

**Comment by jondo** [comment]
Thank you for your solution! From the documentation, I was not aware I could also try `reduce_inequalities`.

**Comment by skirpichev** [comment]
Let me know how I can improve documentaion.

**Comment by jondo** [comment]
In the [inequality solvers doc](http://diofant.readthedocs.io/en/latest/modules/solvers/inequalities.html), some functions (like `reduce_inequalities`) use the verb 'reduce', some use 'solve'. I had focused on the ones with 'solve' to _solve_ the inequality, thinking that the 'reduce' functions are helper functions.

B.t.w., could I also use `solve_rational_inequalities` here? I tried `df.solve_rational_inequalities([[(abs((x - 1)/(x - 5)) - df.Rational(1, 3), '<=')]])`, but this only gives `TypeError: 'Add' object is not iterable`.

**Comment by skirpichev** [comment]
> thinking that the 'reduce' functions are helper functions.

No, "solve_*" functions - are really more low-level stuff.

> I tried df.solve_rational_inequalities([[(abs((x - 1)/(x - 5)) - df.Rational(1, 3), '<=')]]), but this only gives TypeError: 'Add' object is not iterable.

Sure.  Your inequality is not a rational one (i.e. a ratio of polynomial inequalities)..

**Comment by jondo** [comment]
> No, "solve_*" functions - are really more low-level stuff.

Perhaps just add that to the module description?

I notice something else in the docs:
The examples of `reduce_rational_inequalities` and `reduce_abs_inequalities` show that the inequalities can alternatively be given in form of (term, relation) couples. Would it make sense to provide this for all functions (and document it for the module)? At least `reduce_abs_inequality`, which now takes a separate relation argument, should be made matching.
(A different issue, since this one is really about the `solve()` regression?)

**Comment by skirpichev** [comment]
On Thu, Mar 02, 2017 at 04:11:29AM -0800, Robert Pollak wrote:
>    The examples of reduce_rational_inequalities and reduce_abs_inequalities
>    show that the inequalities can alternatively be given in form of (term,
>    relation) couples. Would it make sense to provide this for all functions
>    (and document it for the module)? At least reduce_abs_inequality, which
>    now takes a separate relation argument, should be made matching.

It's matching.  But not for reduce_abs_inequalities - for solve_poly_inequality.

(BTW, there is no reduce_abs_* - there are reduce_piecewise_inequality
and so on.  Please look on the "latest" documentation too, not
only to the stable branch.)

>    (A different issue, since this one is really about the solve()
>    regression?)

Don't worry.  I'll try to fix raised here documentation issues too
or split something out, to a separate issue.

**Comment by jondo** [comment]
> (A different issue, since this one is really about the solve() regression?)
Sorry, I missed your above fix for the regression!

**Comment by jondo** [comment]
> Please look on the "latest" documentation too, not only to the stable branch.

Oops - my bad. I also had the SymPy docs open and mixed them up!

So, if it's OK for you to keep the have separate 'rel' argument of `reduce_piecewise_inequality`, then feel free to close this issue.

**Comment by skirpichev** [comment]
> if it's OK for you to keep the have separate 'rel' argument of reduce_piecewise_inequality

It's a private function now (as all others, except reduce_inequalites), see #458.  Yes, there is apparently some inconsistency in args of private functions of that module, but I don't have a good idea on how to fix this (or function naming, whatever).

Please open an issue, if you know how.

**Comment by jondo** [comment]
Thank you for this cleanup - and generally, for being so responsive :+1: 

>  there is apparently some inconsistency in args of private functions of that module

I think this matters much less than how the public API looks like. I, as a user, only care about this :-) .
