### ISSUE TITLE
Limit infinite recursion

### ISSUE THREAD

**Issue by Upabjojr** [diofant/diofant#558]
```python
n = Symbol('n')
r = Symbol('r', positive=True)
c = Symbol('c')
p = Symbol('p', positive=True)
m = Symbol('m', negative=True)
expr = ((2*n*(n - r + 1)/(n + r*(n - r + 1)))**c +
            (r - 1)*(n*(n - r + 2)/(n + r*(n - r + 1)))**c - n)/(n**c - n)
expr = expr.subs(c, c + 1)
```
Diofant appears unable to handle:
```python
limit(expr, n, oo)
```
Mathematica returns an unevaluated limit.

SymPy raises an exception.

**Comment by skirpichev** [comment]
Parametric limits aren't handled well, see #425.  Different algorithm required, maybe it's even possible to extend the Gruntz algorithm.

**Comment by skirpichev** [comment]
Test coming from sympy/sympy#5172, isn't?  Please note that this limit is tested in the diofant for positive and negative ``c`` separately.

**Comment by Upabjojr** [comment]
Yes, the general case should remain unevaluated. SymPy currently raises an exception.

**Comment by skirpichev** [comment]
I believe, this is a simplest version of the problem:
```
from diofant.series.gruntz import limitinf
x = Symbol('x', real=True, positive=True)
c = Symbol('c')
limitinf(x**c + 1, x)
```

**Comment by skirpichev** [comment]
Ok, I have found a workarround, see #588.  Limit stay unevaluated.

I'm a bit unsure about mrv_leadterm() mods, perhaps instead Expr.as_coeff_exponent() should raise an error (ValueError?), if coeff depends on symbol.
