### ISSUE TITLE
dsolve: modifications to a test changed its meaning

### ISSUE THREAD

**Issue by cbm755** [diofant/diofant#671]
See `test_ode.py: test_C1_function_9239`

It was deliberately supposed to test what happens if you pass function called 'C1'.

I improved the test a bit here: https://github.com/sympy/sympy/pull/9064/commits/458ff7a230abc3d285e4e54b5ae709cb379a3f9e

And I filed sympy issue 15056 to improve it more.

**Comment by skirpichev** [comment]
I did a quick fix in #670 and I would appreciate review.

**Comment by skirpichev** [comment]
Ok, I assume that Colin aren't interested in review.  Will merge #670, when tests pass.

**Comment by cbm755** [comment]
Well, not if I'm expected to on 24 hours notice...
