### ISSUE TITLE
dsolve: `type10` still referred to, but it was dropped

### ISSUE THREAD

**Issue by cbm755** [diofant/diofant#672]
I see you dropped some of the poor ODE code in 14e8188b1e020787509e56272a7189c6df65a9e7

This removed `type10` but some other part of the code still returns the string `type10`: didn't look carefully but problem should've been cut too?

**Comment by skirpichev** [comment]
In principle, classification code is tested for this line.  Someone can provide tested ode solver helper to obtain solution for this match.

I don't think such remnants of removed dsolve helpers should be removed too.
