### ISSUE TITLE
more tests for parser changes

### ISSUE THREAD

**Issue by cbm755** [diofant/diofant#675]
It was noted that your parser changes in c2639dd4032f27b9fcae3e14a0d97cc1e3539e6a for dropping `Symbol.__call__` might be lacking tests.  I added some here if you want them:

https://github.com/sympy/sympy/pull/9064/commits/ed20a72942804a3cfb0e95d883c42b8f7bebf5f2

https://github.com/sympy/sympy/pull/9064/commits/e4869fd331bed5ff82520ccbd8f67fea39794935

(those should obviously be squashed).

BTW, in case it wasn't deliberate, I noticed Diofant changed `srepr(exp(z))` to be `Pow(E, Symbol('z'))`

**Comment by skirpichev** [comment]
> It was noted that your parser changes in c2639dd for dropping Symbol.__call__ might be lacking tests.  I added some here if you want them:

Thank you, I'll think about.  There are parser tests for Function's, but no so many.

> I noticed Diofant changed srepr(exp(z)) to be Pow(E, Symbol('z'))

@cbm755, in the Diofant, ``exp`` is a python function, which returns ``E**x``, just like ``sqrt`` in SymPy.  There was [an attempt](https://github.com/diofant/diofant/pull/540) to implement such beasts as subclasses of ``Pow``, but not so successful so far.
