### ISSUE TITLE
Inconsistency quo vs quo_ground in dense and sparse representations

### ISSUE THREAD

**Issue by skirpichev** [diofant/diofant#702]
Here is an example:
```python
In [1]: e = 2*x + 3                                                                                                                     

In [2]: dense = e.as_poly()                                                                                                             

In [3]: dense.quo(2, auto=False)                                                                                                        
Out[3]: Poly(x, x, domain='ZZ')

In [4]: dense.quo_ground(2)                                                                                                             
Out[4]: Poly(x + 1, x, domain='ZZ')

In [5]: R = ZZ.poly_ring(x)                                                                                                             

In [6]: sparse = R.from_expr(e)                                                                                                         

In [7]: sparse.quo(R.from_expr(2))                                                                                                      
Out[7]: x

In [8]: sparse.quo_ground(2)                                                                                                            
Out[8]: x
```

For sparse representation ``quo()`` and ``quo_ground()`` outputs are equal, but for dense (which currently uses Poly class) - are not.

@jksuom, what do you think (this issue is valid for sympy as well, if you replace from_expr -> from_sympy)?

**Comment by skirpichev** [comment]
> result is unambiguous

There are two different results.  One for sparse and one for dense representations.

**Comment by jksuom** [comment]
If the division is not exact (i.e., the divisor is not a factor of the dividend in the domain in question), then there is no general principle for determining the result. I would remove the high level methods `quo_ground` for both sparse and dense polynomials and use `quo` instead. I think that it makes sense to use the low level method only when it is known that the division is exact.

**Comment by jksuom** [comment]
> Both sparse and dense quo_ground methods are used a lot.

I have not looked at all uses but most of them seem ok. It seems that `quo_ground` on sparse polynomials is not correct for `monic`.
```
>>> R, x = ring('x', ZZ)
>>> (2*x + 1).monic()
x
```

**Comment by skirpichev** [comment]
BTW, difference dense vs sparse traced to 2445aa04a from https://github.com/sympy/sympy/pull/1840.  Commit message a bit cryptic, it's not obvious why this "fix" require a different convention for sparse's quo_ground (which just drop a coefficient, if the division is not exact).

**Comment by jksuom** [comment]
The sparse version of `quo_ground()` seems to have been introduced in https://github.com/sympy/sympy/pull/1840/commits/61874dc20bf9be42b091298d04d6a8ddcda75ef3. I think it was an error not to check for exact division.

**Comment by skirpichev** [comment]
> I think it was an error not to check for exact division.

I think, this was reserved for exquo_ground method (which might be useful for "//" with the right op from the ground domain).

Currently, "/" == "//" for PolyElement.  There is a todo line for ``__floordiv__()`` magic method to be for exquo().  In fact, probably "//" - should be for the current ``quo()`` method behaviour and ``/`` - reserved for ``exquo()``.

**Comment by jksuom** [comment]
> probably "//" - should be for the current quo() method behaviour

I think I could agree with this (assuming that `quo()` would always return a result in the same ring). I am not quite sure about the relationship between `exquo()` and `/`.

**Comment by skirpichev** [comment]
Ok, I will try the following practical plan (which goes to https://github.com/diofant/diofant/pull/720) to fix this issue:
1. Remove usage of quo_ground() outside of polyclasses.py, polytools.py and rings.py (where DMP, Poly and PolyElement are defined)
2. Make PolyElement's quo_ground() be like DMP.quo_ground (== dmp_quo_ground()).
3. Implement PolyElement.exquo_ground() and use this in PolyElement.monic() (to raise ExactQuotientFailed in [your example](https://github.com/diofant/diofant/issues/702#issuecomment-433619312))
4. Don't implement ``/`` on PolyElement's.

Let me know, if you have some thoughts about this proposal.

I also believe, there may be something wrong in default coercion rules of PolyElement.  An example (on the PR #720's branch):
```
In [1]: R, x = ring('x', ZZ)                                                                                                            
In [2]: e = 2*x + 3                                                                                                                     
In [3]: e//2                                                                                                                            
Out[3]: x + 1
In [4]: e//R.from_expr(2)                                                                                                               
Out[4]: x
```
The reason is that in In[3] computation was dispatched to ``quo_ground()`` method and in In[4] - to ``quo()`` method.  However, same happens for the dense representation (DMP class).  I'm planning to use sparse representation instead of DMP for Poly's (see https://github.com/diofant/diofant/issues/711), so - mentioned issue (if it is an issue at all) may be fixed after the PolyElement will became a workhorse for Poly.
