### ISSUE TITLE
dmp_sqf_part(), dmp_sqf_p() and dmp_sqf_list() are wrong for multivariate polynomials

### ISSUE THREAD

**Issue by skirpichev** [diofant/diofant#714]
Simple example:
```
In [1]: R, x, y, z = ring('x y z', ZZ)                                                                                                  

In [2]: f = (x - y)*(z - 1)**2                                                                                                          

In [3]: f.is_squarefree   # same algorithm, as in dmp_sqf_p()                                                                                             
Out[3]: True

In [4]: R.dmp_sqf_part(f)                                                                                                               
Out[4]: x - y

In [5]: R.dmp_sqf_list(f)                                                                                                               
Out[5]: (1, [(x - y, 1)])
```

Apparently, functions are using algorithms, which really work only for univariate polynomials, e.g. [test for a square-free polynomial](https://github.com/diofant/diofant/blob/173ed6de7ab69a36ca209d6e9292d330c126b718/diofant/polys/sqfreetools.py#L27-L30) take formal derivative of poly ``f`` wrt the first argument.

Seems to be a long-standing issue for SymPy, e.g. it affects [this problem](https://github.com/sympy/sympy/issues/5786), though I can't find a dedicated bugreport.

@jksuom, you may want at least to track this problem for SymPy.

**Comment by skirpichev** [comment]
It looks that different algorithms have different assumptions about the output of ``dmp_sqf_*``.  For example, ``dmp_zz_wang()`` do care about input polynomial ``f`` being square-free in the first variable.  While ``dmp_ext_factor()`` seems to be using usual sense of square-free decomposition for multivariate polynomials  (i.e. ``gcd(f, diff(f, x1), diff(f, x2), ...) == 1`` for square-free ``f``).

Maybe there should be functions like ``dmp_sqf_p_in()``, ``dmp_sqf_part_in()``, which will refer to the first sense (but will use ``dmp_diff_in()`` instead of ``dmp_diff()``)?  Current ``dmp_sqf_*`` functions then will be modified to reflect the second notion.

**Comment by jksuom** [comment]
It also seems that the meaning of "square free" can vary on multivariate polynomials: square free either as a polynomial of the first variable or of all variables. For example, `dmp_sqf_p` is only concerned with the first variable:
```
>>> from sympy.polys import ring, ZZ
>>> R, x, y = ring("x,y", ZZ)
>>> R.dmp_sqf_p((x + 1)*y**2)
True
```
This will make the situation even more confusing. I am not sure that there should be an implementation for each variant but the documentation could certainly be better.

**Comment by skirpichev** [comment]
> I am not sure that there should be an implementation for each variant

I think, that ``Out[3]`` from the bug description - could surprise people.  For PolyElement: is_squarefree, sqf_part() and sqf_list() - must use notion of being square-free only to all variables.  Everything else, probably, belongs to different interfaces. For example, user can drop all-but-one generators to the ground domain and then call is_squarefree and friends - this will emulate current behaviour. What do you think?

> the documentation could certainly be better.

I think, there is more then a documentation issue for ``dmp_sqf_*()`` functions.

IIUC, ``dmp_sqf_list()`` must return a full decomposition of ``f``, from which ``f`` can be reconstructed back, like ``dmp_factor_list()`` does.  Which is not the case (see ``Out[5]`` in the bugreport description).  In short, the following invariant was broken:
```
f == R.dmp_sqf_list(f)[0]*sum(p**k for p, k in R.dmp_sqf_list(f)[1])
```
Presently, it puts only numbers to the first entry.  I think it also should include all factors, that are independent on the first variable.

Other mentioned  ``dmp_sqf_*`` methods, probably, are consistent and use meaning of being "square-free" wrt to the first variable.  ``dmp_sqf_part()`` is not broken like ``dmp_sqf_list()``: constants wrt to the first variable could be omitted here, just as numbers.  Documentation should be fixed, of course, for all functions.  Presently, it looks like they do/test a square-free factorization wrt to all variables.

Regarding ``dmp_ext_factor()``, which assume a different notion of being square-free, that leads to bugs like https://github.com/sympy/sympy/issues/5786.  That issue, probably, could be fixed [like this](https://github.com/diofant/diofant/pull/713/commits/619787be0eb8da8786c8aec4a105745885867dc1).  Other use-cases of ``dmp_sqf_*`` are in factortools.py (and seems to be fine), in rootisolation.py (which uses univariate case, no issue could be there) and in the integrals module (which also uses only univariate polynomials, if I don't miss something).

**Comment by skirpichev** [comment]
Alternative ``dmp_ext_factor()`` fix: #717

**Comment by skirpichev** [comment]
``dmp_sqf_part()`` seems to be a low-level method, not used outside of factortools & rootisolation modules.  (And, after all, it can be easily reconstructed from the ``dmp_sqf_list()``). So, I think, ``sqf_part()`` methods can be safely removed from high-level classes (i.e., Poly and PolyElement).

**Comment by jksuom** [comment]
I would consider `sqf_list()` as an "iterated" `sqf_part()`. It is true that the latter can be derived from the former but that is less efficient. I think that the relationship between `coeffs()` and `LC()` or `TC()` is similar. The latter can be derived from the former but it is still sometimes useful to have them as separate methods.

**Comment by skirpichev** [comment]
On Fri, Nov 16, 2018 at 01:19:41AM -0800, Kalevi Suominen wrote:
>    I would consider sqf_list() as an "iterated" sqf_part(). It is true that
>    the latter can be derived from the former but that is less efficient. I
>    think that the relationship between coeffs() and LC() or TC() is similar.
>    The latter can be derived from the former but it is still sometimes useful
>    to have them as separate methods.

Ok, fair enough.  (Although, I can't suggest applications of this method
outside of real root isolation.)

It seems, that current algorithm (Yun's for char 0 polys) can be easily
extended to any subset of polynomial ring generators.  See
https://github.com/diofant/diofant/pull/713
where this was implemented for all generators.

So, instead of dmp_sqf_p, dmp_sqf_part, dmp_sqf_list...  I would suggest
low-level interfaces like
dmp_sqf_p_in(f, N, u, K)
dmp_sqf_part_in(f, N, u, K)
dmp_sqf_part_list_in(f, N, u, K)
...
where N - list of generator indexes, e.g.
current dmp_sqf_p(f, u, K) will be transformed
to dmp_sqf_p_in(f, [0], u, K).

For high-level classes (DMP, PolyElement, Poly), I think, there should
be only case of all generators (N = list(range(u))).  It also seems, the
current codebase doesn't require is_sqf/is_squarefree (and companion
methods) to have same meaning as dmp_sqf_p().

**Comment by skirpichev** [comment]
I also not sure if it worth keeping ``all`` kwarg for ``dmp_sqf_list()`` (and ``dmp_sqf_list_include()``).

**Comment by jksuom** [comment]
It looks like `all` is used nowhere. It is not implemented except for `gf_sqf_list`, and even there we have these lines:

    if all:
        raise ValueError("'all=True' is not supported yet")

 So it probably could be removed without breaking anything.

**Comment by skirpichev** [comment]
On Sun, Nov 18, 2018 at 01:30:44AM -0800, Kalevi Suominen wrote:
>    It looks like all is used nowhere.

It's used.  Quick sympy grep:
$ git grep 'sqf.*(.*all=True'
sympy/integrals/rationaltools.py:            c, h_lc_sqf = h_lc.sqf_list(all=True)
sympy/integrals/risch.py:            h_lc_sqf = h_lc.sqf_list_include(all=True)
sympy/polys/partfrac.py:    for d, n in Q.sqf_list_include(all=True):
sympy/polys/polytools.py:        >>> Poly(f).sqf_list(all=True)
sympy/polys/polytools.py:        >>> Poly(f).sqf_list_include(all=True)
sympy/polys/sqfreetools.py:    >>> R.dup_sqf_list(f, all=True)
sympy/polys/sqfreetools.py:    >>> R.dup_sqf_list_include(f, all=True)
sympy/polys/sqfreetools.py:    >>> R.dmp_sqf_list(f, all=True)
sympy/polys/sqfreetools.py:    >>> R.dmp_sqf_list_include(f, all=True)

Non-trivial cases are in rationaltools.py, risch.py and partfrac.py.

**Comment by skirpichev** [comment]
> Looping over the returned list could be simpler if all levels are included.

What do you mean by "all levels"?  Including the constant coefficient?  For this, there are dmp_sqf_list_include() method.  Unless I miss something, the net result of dmp_sqf_list(all=True) will be the list of factors with added unit factors.  And the first factor will have multiplicity 1 (which fact may be later useful for dmp_sqf_list_include()).  Not sure that any shown above examples in integrals module or partfrac do really care about trivial factors.

> So, I now think that all could be left as is.

It could be.  But if it's possible to remove this kwarg, I believe, I should do this.

**Comment by jksuom** [comment]
> Including the constant coefficient?

It does not look reasonable to include that in `sqf_list` when `sqf_list_include` is available.

**Comment by skirpichev** [comment]
Not sure what's better for property name: ``is_sqf`` or ``is_squarefree``.  I think, that Poly/PolyElement/DMP should be consistent in this aspect too.  I prefer long version.  So far, ``is_sqf`` is only one abbreviation across ``is_foo`` methods in mentioned classes.

**Comment by jksuom** [comment]
Or another variant: `is_sqfree`. `is_sqf` does not feel good.

**Comment by skirpichev** [comment]
A work in progress for this issue: https://github.com/diofant/diofant/pull/719

**Comment by skirpichev** [comment]
An alternative: https://github.com/diofant/diofant/pull/726

That PR corrects also `dmp_sqf_norm`, which now search for square-free norm wrt to all variables.

**Comment by jksuom** [comment]
The name `FiniteField` for `FF(p)` is wrong in SymPy if `p` is not a prime as it is not even an integral domain. That is an issue that clearly should be fixed. But even if it is a field, `dmp_sqf_p` looks wrong. It should take care of the case where the derivative is zero (and return False unless the polynomial is constant).

**Comment by skirpichev** [comment]
> But even if it is a field, dmp_sqf_p looks wrong.

Hmm, If it's a perfect field, `gcd(f, f')==1` - should be a necessary condition for being sqf, isn't?  It's unclear for me how zero derivatives would break `dmp_sqf_p()` algorithm.  At least, as this was implemented in #726.

BTW, `gf_sqf_p()` could be removed, as it clearly assume the case of `FF(p)` with prime `p` and duplicate algorithm in ``dmp_sqf_p()`` (in univariate case).

**Comment by jksuom** [comment]
> gcd(f, f')==1 should be a necessary condition for being sqf

I think you are right. In fact, it should also be a sufficient condition. What I had in mind was the squarefree part. There one has to consider p'th powers having zero derivative.

**Comment by skirpichev** [comment]
> What I had in mind was the squarefree part.

This is routed to `gf_sqf_list()` and (as far as I can see) properly take that issue into account.

**Comment by skirpichev** [comment]
@jksuom, I'm glad that you are using part of this work in https://github.com/sympy/sympy/pull/19367, but I'm afraid, this will not be enough for fixing `dmp_ext_factor()`.  Other methods in the sqfreetools also must be adapted, especially `sqf_norm()`.  I'm pretty sure, your "contributors" aren't realize that these methods are connected...

I'm rewriting the factortools module right now and I would appreciate if you suggest some reference for the multivariate generalization of the Trager method, which is used in the Diofant.  The current implementation (after #726) is correct, I think.

**Comment by jksuom** [comment]
I had forgotten all about this. I suggested some patches but I feel uncomfortable about `dmp_ext_factor`. I am not at all sure that the method that works with univariate polynomials would also work there.

**Comment by skirpichev** [comment]
> I am not at all sure that the method that works with univariate polynomials would also work there.

@jksuom, this was mentioned in the original Trager's paper.  Yet, maybe my proof is wrong somewhere.

Also, this method was implemented in the rings java library, see https://rings.readthedocs.io/en/latest/algorithms.html and https://github.com/PoslavskySV/rings/blob/d5f2718663f6aebc7be3a49d90db46407b03d1bd/rings/src/main/java/cc/redberry/rings/poly/multivar/MultivariateFactorization.java#L2778

I think that `sqf_norm()` modifications (together with other `*_sqf_*` methods, to support all variables) are correct.  Potential problem may be in the norm factoring and/or the final backsubstitution phase.

**Comment by jksuom** [comment]
> this was mentioned in the original Trager's paper.

Indeed it is mentioned at the end though there are no details. I hadn't noticed before. Thanks for pointing out and the references. I'll have to think about the proof...

**Comment by skirpichev** [comment]
I think, the point of the last section of Trager's paper, that multivariate extension is trivial (given that
we can factor multivariate polynomials with integer coefficients).  All related paper proofs (sec. 2) seems to be working.

**Comment by skirpichev** [comment]
@oscarbenjamin, I'm glad to see this was fixed in the SymPy recently.

It seems, https://github.com/sympy/sympy/issues/5786 could be closed.

**Comment by oscarbenjamin** [comment]
Thank Sergey.

I don't know if you have already seen this but RIP Kalevi (@jksuom):
https://groups.google.com/g/sympy/c/dLlg8l_btTs/m/o1azuhGMAAAJ

**Comment by skirpichev** [comment]
Yeah, I've seen this thread, just can't reply.  He helped me as well and (I hope) I've learned a lot.

**Comment by oscarbenjamin** [comment]
He is sorely missed.

It is a strange thing that on GitHub we have these disjointed conversations over periods of years. I expect that we will bump into old conversations with Kalevi like this for a long time to come.
