### ISSUE TITLE
dup_count_real_roots() is broken for composite domains

### ISSUE THREAD

**Issue by skirpichev** [diofant/diofant#745]
This is wrong:
```
In [16]: R1 = ZZ.poly_ring(y).poly_ring(x)

In [17]: R1.dup_count_real_roots(R1.from_expr(x**7 + y*x + 1))
Out[17]: 1
```
That's easy to demonstrate even for real `y`:
```
In [18]: R2 = ZZ.poly_ring(x)

In [19]: R2.dup_count_real_roots(R2.from_expr(x**7 + 2*x + 1))
Out[19]: 1

In [20]: R2.dup_count_real_roots(R2.from_expr(x**7 - 2*x + 1))
Out[20]: 3
```

Same issue is valid for SymPy:
```
In [1]: Poly(x**7 + x*y + 1, x)
Out[1]: Poly(x**7 + y*x + 1, x, domain='ZZ[y]')

In [2]: _.count_roots()
Out[2]: 1

In [3]: Poly(x**7 + x*2 + 1, x).count_roots()
Out[3]: 1

In [4]: Poly(x**7 - x*2 + 1, x).count_roots()
Out[4]: 3
```

Simple solution: add a quick exit for Composite domains.  Probably, raising `DomainError` would be fine.

**Comment by skirpichev** [comment]
@jksuom, you may be interested in, as issue is clearly valid for sympy too.  Simple fix: #741 (unfortunately, will require some substantial changes in rationaltools module).

**Comment by jksuom** [comment]
DomainError should probably be raised also for many non-composite domains. Sturm's theorem only works on (real closures of) ordered fields.

**Comment by skirpichev** [comment]
Yes, I think, that it does make sense to sanitize input for functions in rootisolation module more strictly.

Probably, in practical terms this will mean to raise the DomainError exception if the domain is not ComplexAlgebraicField (which stands for `real + I*real`), RealAlgebraicField or RationalField.  (Or, in short - a ComplexAlgebraicField, for which RealAlgebraicField and RationalField will be eventually subclasses of.)

**Comment by skirpichev** [comment]
Yes, this should be handled separately.  Currently, the whole case of algebraic field is [implemented](https://github.com/diofant/diofant/blob/65bf0fda7a8992927484d3a6057d05156e30b652/diofant/polys/rootisolation.py#L620-L621) with help of `dup_isolate_real_roots()`, by direct counting of founded roots.  

Apparently, this is not efficient.  In fact, I think that case of real algebraic domains could be handled with the current Sturm's theorem-based code right now.
