### ISSUE TITLE
jordan_form calc_transformation=False not working (and docs are wrong?)

### ISSUE THREAD

**Issue by cbm755** [diofant/diofant#774]
`J = A.jordan_form(calc_transformation=False)` still returns both P and J.  Maybe it should either compute and discard P or `raise NotImplemented` when False is passed.

The docs for `jordan_cells` say:
```
        Notes
        =====

        Calculation of transformation P is not implemented yet.
```
Am I right that that should be "Skipping the calculation of the transformation is not implemented"?

**Comment by cbm755** [comment]
oh sorry, this is legacy stuff---I thought it was regressions from the fork when I filed this.

**Comment by skirpichev** [comment]
> I thought it was regressions from the fork when I filed this.

Not a problem.  If this was solved in sympy since the fork started - I always can port that work.

Perhaps, I should do another round of regular backporting work (latest such PR is #598).

**Comment by skirpichev** [comment]
BTW @cbm755, I believe sympy has same issue, see [same method](https://github.com/sympy/sympy/blob/dc1cad9811eacfdd73a9dee5c66c093d23e1edb9/sympy/matrices/matrices.py#L2268-L2270).  Option just get ignored.

I'm thinking about reordering output arguments, calc_transformation will be an option to skip the last one (transformation P). What do you think?
