### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by skirpichev** [diofant/diofant#776]
There are few places to put images:
- [x] Top left corner of https://diofant.readthedocs.io/ (see e.g. https://sphinx-rtd-theme.readthedocs.io/)
- [x] favicon.ico.
- [x] logo for pdf logs
- [x] Organization profile on the Github (at least 200x200px)
- [x] ~~repository’s social media preview (640×320px - 1280×640px for best display)~~

**Comment by richardbmx** [comment]
@skirpichev   Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by skirpichev** [comment]
> I can present some modern ideas that would improve the appearance and image of your project

Any help would be appreciated.  But keep in mind - there is currently no images to improve, apparently this was not clear from beginning...

There are few places, where such images could be placed.  First, as a project homepage we use https://diofant.readthedocs.io/, where the docs live.  It uses [sphinx-rtd-theme](https://sphinx-rtd-theme.readthedocs.io/en/latest/index.html) sphinx theme, which support logo at the top left corner of the page, [see example](https://docs.readthedocs.io/en/stable/).  Favicon could be specified too.  And there is the [profile on github](https://github.com/diofant), which has place for organization's avatar.

**Comment by richardbmx** [comment]
@skirpichev  perfect I can do all that for you. can you tell me what the project is about and so be able to do something that is consistent with it

**Comment by skirpichev** [comment]
Ok, I did some simple version in #852.  Let me know if you think that you could improve something.
