### ISSUE TITLE
Support multivariate inequalities in reduce_inequalities()

### ISSUE THREAD

**Issue by mpjuers** [diofant/diofant#836]
https://github.com/sympy/sympy/issues/9479 suggests it's possible to solve multivariable inequalities in diofant, however I get `ValueError: Only expressions or equalities supported, got x + y > 1` when I attempt to solve a multivariable inequality.

Steps to reproduce:

    import diofant as df
    df.var('x y')
    df.solve(x + y > 1, [])

**Comment by skirpichev** [comment]
In short, no.

To achieve this goal, something like the Collins CAD algorithm should be implemented first.  See e.g. [this](https://github.com/sympy/sympy/wiki/GSoC-2015-Application-Luv-Agarwal:-Cylindrical-Algebraic-Decomposition) proposal of SymPy.  The CAD require more stuff, e.g. solving polynomial equations with algebraic coefficients, comparisions of real algebraic numbers and so on. Diofant is in a better position than SymPy - I think almost everything required by CAD already there (maybe the [FOL pr](#703) - the only thing missing).  Yet, CAD algorithm itself is a good challenge to implement.

So, for now - only univariate equations are supported.  E.g.:
```python
In [17]: df.var('x y', real=True)
Out[17]: (x, y)

In [18]: df.reduce_inequalities(x + y > 1, [x])
Out[18]: -y + 1 < x
```
Note, that `solve()` - the interface for solving algebraic equations in diofant, it returns a list of dictionaries (ready to be `.subs()`'tituted).  It's different from SymPy and more like Mathematica's Solve vs Reduce.

**Comment by mpjuers** [comment]
More complicated input (below) is raising `TypeError: __str__ returned non-string (type tuple)`.

    expr = -(-Y_2*b_1*b_x - Y_2*b_1*beta_2*c + Y_2*b_x*beta_1*c + Y_2*beta_1*beta_2*c**2 - b_1*beta_1*c - b_1*u_x - b_x*be
ta_1*c + b_x*u_1 + beta_1*c*u_1 + beta_1*c*u_x)/(-b_1 + beta_1*c)
    df.reduce_inequalities(expr > 0, [b1])

**Comment by skirpichev** [comment]
Are you sure about TypeError?  I got NotImplementedError on v0.10.0 and in the latest development version:
```python
In [1]: import diofant as df

In [2]: df.__version__
Out[2]: '0.10.1.dev377+gbfd2d7d673'

In [3]: df.var('Y_1 Y_2 b_1 b_2 b_x beta_1 beta_2 c u_1 u_2 u_x')
Out[3]: (Y₁, Y₂, b₁, b₂, bₓ, β₁, β₂, c, u₁, u₂, uₓ)

In [4]: expr = -(-Y_2*b_1*b_x - Y_2*b_1*beta_2*c + Y_2*b_x*beta_1*c + Y_2*beta_1*beta_2*c**2 - b_1*beta_1*c - b_1*u_x - b_x*beta_1*c + 
      : b_x*u_1 + beta_1*c*u_1 + beta_1*c*u_x)/(-b_1 + beta_1*c)

In [5]: df.reduce_inequalities(expr > 0, [b_1])
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-5-1bd787c87707> in <module>
----> 1 df.reduce_inequalities(expr > 0, [b_1])

~/src/diofant/diofant/solvers/inequalities.py in reduce_inequalities(inequalities, symbols)
    544 
    545     # solve system
--> 546     rv = _reduce_inequalities(inequalities, symbols)
    547 
    548     # restore original symbols and return

~/src/diofant/diofant/solvers/inequalities.py in _reduce_inequalities(inequalities, symbols)
    462             if len(common) == 1:
    463                 gen = common.pop()
--> 464                 other.append(solve_univariate_inequality(Relational(expr, 0, rel), gen))
    465                 continue
    466             else:

~/src/diofant/diofant/solvers/inequalities.py in solve_univariate_inequality(expr, gen, relational)
    409     start = -oo
    410     sol_sets = [S.EmptySet]
--> 411     reals = _nsort(set(solns + singularities), separated=True)[0]
    412     for x in reals:
    413         end = x

~/src/diofant/diofant/polys/polyutils.py in _nsort(roots, separated)
     43             return [[], [r]]
     44     if not all(r.is_number for r in roots):  # pragma: no cover
---> 45         raise NotImplementedError
     46     # see issue sympy/sympy#6137:
     47     # get the real part of the evaluated real and imaginary parts of each root

NotImplementedError: 
```

**Comment by mpjuers** [comment]
This is interesting. If I extract the object of interest (in this case `df.reduce_inequalities(list(eigs.keys())[0]), [b_1]`), I get the `ValueError`, but if I paste in the equivalent `print(list(eigs.keys())[0]), [b_1])` output, I get the `NotImplementedError`. I will look into this further and get back to you.

**Comment by skirpichev** [comment]
This depend on the CAD implementation (https://github.com/diofant/diofant/issues/1045)

**Comment by jondo** [comment]
@mpjuers, what is the expected result of your [more complicated input](https://github.com/diofant/diofant/issues/836#issuecomment-488394894)?

**Comment by skirpichev** [comment]
FYI, after #1063 we got support for multivariate linear inequalities:
```
In [1]: reduce_inequalities([x >= 0, 2*x + 4*y <= 14, x - 2*y <= 1])
Out[1]: 
            x   1                 x   7
x ≥ 0 ∧ y ≥ ─ - ─ ∧ x ≤ 4 ∧ y ≤ - ─ + ─
            2   2                 2   2
```

I believe, this issue may be closed after minor code refactoring (we need to be sure, that other multivariate inequalities produce something like the NotImplementedError exception).
