### ISSUE TITLE
nth-roots are not pretty printed

### ISSUE THREAD

**Issue by cbm755** [diofant/diofant#888]
`pprint(7**(1/pi))` doesn't pretty print the `pi`.  See
https://github.com/sympy/sympy/pull/17620

Feel free to cherry-pick!

(Some of this doesn't effect diofant b/c `exp(-1)` is a `Pow`).

**Comment by skirpichev** [comment]
Hmm, are you sure that nth-root notation is common for non-integer denominators?  Wikipedia, for example, seems using it only for positive integer n.

A simpler alternative:
```diff
$ git diff
diff --git a/diofant/printing/pretty/pretty.py b/diofant/printing/pretty/pretty.py
index 4068af5e9d..8d7398f7ea 100644
--- a/diofant/printing/pretty/pretty.py
+++ b/diofant/printing/pretty/pretty.py
@@ -1331,7 +1331,7 @@ def _print_Pow(self, power):
             if e == -1:
                 return prettyForm("1")/self._print(b)
             n, d = fraction(e)
-            if n == 1 and d.is_Atom and not e.is_Integer:
+            if n == 1 and d.is_Atom and e.is_Rational:
                 return self._print_nth_root(b, e)
             if e.is_Rational and e < 0:
                 return prettyForm("1")/self._print(Pow(b, -e, evaluate=False))
```

**Comment by skirpichev** [comment]
In fact, I'm not fan of this:
```
In [3]: Pow(x, 1/3000000)
Out[3]: 
3000000___
     ╲╱ x 
```

IMHO, this unicode notation expects no more than one letter

An this does look ugly in the Jupyter Notebook too:
![Screenshot from 2019-09-18 14-24-41](https://user-images.githubusercontent.com/2155800/65144610-5fa57b80-da20-11e9-846d-355f663254c5.png)

**Comment by cbm755** [comment]
Jupyter thing is LaTeX printer not pretty I think.

How about in both pretty and latex we use root notation for integers with at most 3 digits?  Or at most two digits?

**Comment by cbm755** [comment]
> Looks as magic numbers.

Well, if its going to be magic, it might as well be 1.

In your screenshot above, I looks like at most 3 would render ok in Jupyter without overlapping the radical.

**Comment by cbm755** [comment]
What about?
```
n = Symbol('n', positive=True, integer=True)                                                 
Pow(7, 1/n)
```
I think `$\sqrt[n]{7}$` would be desirable in that case.

So maybe Rational is too strict?

**Comment by skirpichev** [comment]
> it might as well be 1

Yes.  But I would like to avoid magic numbers in the code.

> I looks like at most 3 would render ok in Jupyter without overlapping the radical.

In fact, LaTeX output seems to be really broken only for much more complex expressions, e.g. with fractions (like ``\sqrt[\pi^2 + \frac{1}{\pi}]{2}``):
![1](https://user-images.githubusercontent.com/2155800/65177890-50deb900-da60-11e9-9237-5a159a066950.png)

Integers of arbitrary length looks readable (MathJax has bug), but I'm not sure how good such radicals as part of more complex expressions will be rendered...
![2](https://user-images.githubusercontent.com/2155800/65177960-74096880-da60-11e9-9070-2d8ce7b530d5.png)

Another option may be using nth root notation only for square, cube and fourth root, i.e. when there are Unicode symbols for that.

> I think ``$\sqrt[n]{7}$`` would be desirable in that case.

It might be fine for ``\sqrt[\pi]{7}`` as well, but I'm not sure about criteria.  Single-letter symbol?

**Comment by cbm755** [comment]
Maybe these should print as radicals:
1.  `x**(1/n)` where n is single-digit Integer
2.  `x**(1/n)` where n is a single-character Symbol.

Here "single" could be replaced with a different magic number (3?) if desired.

Something like:
```
                if e.is_Rational:
                    if e.num == 1 and not e.denom == 1 and abs(e.denom) <= 9:
                        return self._print_nth_root(b, e.denom)
                else:
                    n, d = fraction(e)
                    if n == 1 and d.is_Symbol:
                        dp = self._print(d)
                        if dp.height() == 1 and dp.width() == 1:
                            return self._print_nth_root(b, dp)
```

**Comment by skirpichev** [comment]
Maybe unify both cases by checking n==1 and then for dp?

**Comment by cbm755** [comment]
yes, currently playing with:
```
                n, d = fraction(e)
                if n == 1 and (d.is_Symbol or (d.is_Integer and d != 1)):
                    dp = self._print(d)
                    if dp.height() == 1 and dp.width() <= 3:
                        return self._print_nth_root(b, dp)
```
(here magic number is 3)

**Comment by cbm755** [comment]
Magic number 3 is relatively satisfying:
```
>>> z = Symbol("x_17")
>>> pprint(7**(1/z))                                                                  
x₁₇___
 ╲╱ 7 
>>> pprint(7**(1/z), use_unicode=False)                                               
  1  
 ----
 x_17
7    
```

**Comment by skirpichev** [comment]
Probably, ``d.is_Symbol ...`` checks could be omitted.

**Comment by skirpichev** [comment]
BTW, it looks you have some unsuccessful experiments with overline and "short" unicode square roots in https://github.com/sympy/sympy/pull/9234?

**Comment by cbm755** [comment]
Yeah SymPy does `√17` for integers and short symbols.  Do you want that too?  Its an easy fix.

**Comment by cbm755** [comment]
> `d.is_Symbol` check could be omitted.

It depends what you want to happen for `x**(1/EulerGamma)` and `x**(1/pi)`...

**Comment by cbm755** [comment]
I should clarify: AFAICS, the choices are `is_Atom`, `is_Symbol` or none.  This effects what happens in each of these:
```
x**(1/pi)  and  x**(1/EulerGamma)
x**(1/Symbol('n'))
x**(1/Integer(7))
```
Maybe there are there are other cases I haven't thought of.

**Comment by skirpichev** [comment]
> Yeah SymPy does √17 for integers and short symbols.

I saw this, and that's look ambiguous.  To me, overline seems a required things here.  Unfortunately, it doesn't look right (I tried ``\N{OVERLINE COMBINED}``).

> It depends what you want to happen for x**(1/EulerGamma) and x**(1/pi)...

In the unicode case - both symbols use a single letter...

**Comment by cbm755** [comment]
Indeed, but they are not integer...  If you're ok with irrational roots then the logic can simplify.

**Comment by skirpichev** [comment]
On Wed, Sep 18, 2019 at 02:32:39PM -0700, Colin B. Macdonald wrote:
>    If you're ok with irrational roots
>    then the logic can simplify.

If we allow symbols in denominators - we should accept
irrational numbers as well.
