### ISSUE TITLE
Characteristic equation root power mismatch on rsolve

### ISSUE THREAD

**Issue by limitedeternity** [diofant/diofant#923]
![Screenshot at Nov 30 11-43-00](https://user-images.githubusercontent.com/24318966/69898244-87418a00-1367-11ea-8dd4-c52243f36853.png)

![Screenshot at Nov 30 11-43-12](https://user-images.githubusercontent.com/24318966/69898246-8c063e00-1367-11ea-8110-db245b4e824a.png)

Why `n-1`?

**Comment by limitedeternity** [comment]
Sympy solves the second relation correctly:
![Screenshot at Nov 30 11-51-18](https://user-images.githubusercontent.com/24318966/69898260-c66fdb00-1367-11ea-97ea-a5816203ff7c.png)

While the first one's solution is a complete failure:
![sympy](https://user-images.githubusercontent.com/24318966/69898266-fa4b0080-1367-11ea-9cb1-cdde04c144ae.png)

**Comment by skirpichev** [comment]
Hmm, I fail to see a wrong result here.  Both `Out[19]` and `Out[16]` are correct:
```python
In [11]: e = a(n + 3) + 10*a(n + 2) + 32*a(n + 1) + 32*a(n)
       : s = rsolve(e, a(n))
       : pprint(s)
       : e.subs({a: Lambda(n, s)}).expand() == 0
    n          n          n - 1     
(-2) ⋅C₀ + (-4) ⋅C₁ + (-4)     ⋅C₂⋅n
Out[11]: True

In [12]: e2 = a(n + 2) + 4*a(n + 1) + 4*a(n)
       : s2 = rsolve(e2, a(n))
       : pprint(s2)
       : e2.subs({a: Lambda(n, s2)}).expand() == 0
    n          n - 1     
(-2) ⋅C₀ + (-2)     ⋅C₁⋅n
Out[12]: True
```
But `Out[17]` is looking better (in this example, `C1` can absorb 1/2), so it does make sense to implement somehow simplification of arbitrary constants in the `rsolve()` output.  Right now, it's possible to reuse `constant_renumber()` and `constantsimp()` from the ode module, but certainly this is not a best way to do this (see https://github.com/sympy/sympy/issues/4435).  Patches welcome.

PS: Please avoid posting screenshots, if possible.  Text copy-paste is preferred.

**Comment by skirpichev** [comment]
Some examples of simplification:
```python
In [22]: pprint(s)
       : pprint(constantsimp(s.expand(), [C0, C1, C2]))
    n          n          n - 1     
(-2) ⋅C₀ + (-4) ⋅C₁ + (-4)     ⋅C₂⋅n
    n          n          n     
(-2) ⋅C₀ + (-4) ⋅C₁ + (-4) ⋅C₂⋅n

In [23]: pprint(s2)
       : pprint(constantsimp(s2.expand(), [C0, C1, C2]))
    n          n - 1     
(-2) ⋅C₀ + (-2)     ⋅C₁⋅n
    n            
(-2) ⋅(C₀ + C₁⋅n)
```
As you see, the last output - match SymPy's `Out[17]`.

**Comment by skirpichev** [comment]
Simplification with `constantsimp()` now implemented in https://github.com/diofant/diofant/pull/921.  Feel free to play with this code.

**Comment by limitedeternity** [comment]
👌
