### ISSUE TITLE
Add quick tests in field_isomorphism() to check the possibility of the isomorphism

### ISSUE THREAD

**Issue by skirpichev** [diofant/diofant#942]
In the SymPy (and in the Diofant before), there are is_isomorphism_possible() helper, which doesn't work properly.

An example:
```python
In [1]: from diofant.polys.numberfields import (field_isomorphism,
      :                                         is_isomorphism_possible)
      : 

In [2]: a = QQ.algebraic_field(sqrt(2))

In [3]: e = QQ.algebraic_field(sqrt(2) + sqrt(3) + sqrt(7))

In [4]: field_isomorphism(a, e)
Out[4]: [1/80, 0, -1/2, 0, 59/20, 0]

In [5]: is_isomorphism_possible(a, e)
Out[5]: False
```

**Comment by skirpichev** [comment]
@jksuom, this happens for sympy too.  Unless I misunderstand something, this is a wrong answer.

**Comment by jksuom** [comment]
It looks like the algorithm was not properly tested. This test, in particular, looks wrong:
https://github.com/diofant/diofant/blob/40604057e1436253ed18e2d63dac4371ce4f1462/diofant/polys/numberfields.py#L741
It is the one that leads to the wrong answer.

I would have expected that the test would have been based on the divisibility properties of discriminants: The discriminant of the extension field, `db` is a multiple of `da**k` where `k = m//n` is the relative degree of the extension. I don't understand how the condition above could show this.

**Comment by skirpichev** [comment]
An easy solution would be removing this function, it's unused.  But it could be used by field_isomorphism().

**Comment by jksuom** [comment]
If `b` defines an extension of `a`, then the discriminants satisfy the transitivity relation `db = N*da**k` where `k = m//n` is the relative degree and `N` is the norm of the relative discriminant (see https://en.wikipedia.org/wiki/Discriminant_of_an_algebraic_number_field#Relative_discriminant).
I think that a reasonable quick test would be

    return db % da**k == 0

as `N` is an integer. That would also be valid in case `m == n`.

**Comment by skirpichev** [comment]
BTW, the minpoly discriminant is used in the code right now.  IIRC, it's not the same as the discriminant of the algebraic number field.

**Comment by jksuom** [comment]
That is true. The minpoly discriminant is the same only if the root generates the ring of all integers. Maybe that is why the test is so hard to understand. I may try to consider only those primes that appear in the minpoly discriminants with the same multiplicity as in the field discriminants.

**Comment by jksuom** [comment]
It seems that it is possible to find some information about the field discriminant D if the polynomial discriminant d is known. We know that d is a multiple of D so that it may have prime factors that do not divide D, or prime factors to a higher power than in D. However there is one case where the powers are the same. If d has a prime factor p whose square does not divide d, then p also divides D.
I think that this could be applied in a quick test: if `da % p == 0` but `da % p**2 != 0`, then `Da % p == 0` and therefore we should have `Db % p**k == 0`, and also `db % p**k == 0`, if `b` is an extension of `a`. I cannot make sense of the condition `(da % p) % 2` but it looks like it is vaguely related.

**Comment by skirpichev** [comment]
This sounds like a _positive_ test, c.f. the [current one](https://github.com/sympy/sympy/blob/cb214699949c16fedb698aac030e80d84ed97d66/sympy/polys/numberfields.py#L918).

**Comment by skirpichev** [comment]
I believe, I have found the source of the broken test in the Cohen book.  Not sure if it worth doing factorint() vs using the prime sieve.  In the sympy [both tests](https://github.com/sympy/sympy/blob/516fa83e69caf1e68306cfc912a13f36c434d51c/sympy/polys/numberfields.py#L935) seems to be wrong.  The first one should check instead the exponent of the prime factor and the second one must be inverted.  See e.g. fe5bc51.
